;@using "rfc4825.bnf"

xcap-path          =  "/xcap-root/" 
                      (
                          generic
                        / resource-lists
                      )
                      [ "/" document-name ]

generic            =  path-a-uid "/" ( path-global / path-items )
path-a-uid         =  a-uid
path-global        =  "global"
path-items         =  a-uid "/" path-item
path-item          =  *(a-uid-unreserved / ":" / "@" / ".")
document-name      =  a-uid / "index"


resource-lists       =  "resource-lists/users/sip:" username "@" domain
username             =  *(unreserved)
domain               =  *(unreserved)
