;@using "rfc4825.bnf"

xcap-path          =  "/" "xcap-root" 
                      "/" path-a-uid 
                      "/" ( path-global / path-items )
                      [ "/" document-name ]

path-a-uid         =  a-uid / "xcap-caps" / "resource-lists" / "rls-resources"
path-global        =  "global"
path-items         =  a-uid "/" path-item
path-item          =  *(a-uid-unreserved / ":" / "@" / ".")
document-name      =  a-uid / "index"

